setting:
  name: "kitti_batch_base"
  output_root: "/mnt/nfs/experiments/"
  pc_path: "/mnt/nfs/KITTI-360/data_3d_raw/2013_05_28_drive_0005_sync/velodyne_points/data"
  label_path: "/mnt/nfs/KITTI-360/data_3d_labels/2013_05_28_drive_0005_sync/labels" # optional for semantic mapping
  pose_path: "/mnt/nfs/KITTI-360/data_poses/2013_05_28_drive_0005_sync/poses.txt"
  calib_path: "/mnt/nfs/KITTI-360/calibration/velo2pose.txt"
  load_model: False
  load_mlp: True
  load_tree: True
  model_path: ""
  sem_model_path: ""
  geo_model_path: ""
  first_frame_ref: False
  kitti360: True
  begin_frame: 30
  end_frame: 3000
  every_frame: 10 # 1 means does not skip
  device: "cuda"
  gpu_id: "0"
semantic:
  semantic_aware: False
pos_enc:
  use_pe: False
  pe_levels: [0, 1]
  use_gaussian_pe: False  # use Gaussian Fourier or original log positional encoding
  pos_encoding_freq: 200  # 200
  pos_encoding_band: 5  # if 0, without encoding
process:
  min_range_m: 3.0
  pc_radius_m: 50.0 # distance filter for each frame
  min_z_m: -10.5
  rand_downsample: False # use random or voxel downsampling
  vox_down_m: 0.05
  rand_down_r: 0.2
  rand_down_way: "semantic" # posssible values: "random", "uniform", "farthest", "semantic", "inverse_semantic"
  min_down_r: 0.05
  with_contour: True
  contour_mode: "semantic"  # "semantic" or "distance"
  contour_delta: 0.3  # only for "distance" mode
sampler:
  surface_sample_range_m: 0.3
  surface_sample_n: 3
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 0.8
  free_sample_n: 3
octree:
  leaf_vox_size: 0.3
  tree_level_world: 12
  tree_level_feat: 3
  feature_dim: 8
  poly_int_on: True
  octree_from_surface_samples: True
decoder:
  mlp_level: 2
  mlp_hidden_dim: 32
  freeze_after_frame: 0
  decoder_type: "base"
loss:
  ray_loss: False
  main_loss_type: sdf_bce # select from sdf_bce (our proposed), sdf_l1, sdf_l2, dr, dr_neus
  sigma_sigmoid_m: 0.1
  loss_weight_on: False
  behind_dropoff_on: False
  ekional_loss_on: True
  weight_e: 0.1

  semantic_decomposition_loss: False
  contrastive_loss_margin: 0.1
  contrastive_w: 0.1
continual:
  continual_learning_reg: False # using incremental mapping with regularization
  lambda_forget: 0 # the larger this value, the model would be less likely to forget
  window_replay_on: False # replay within the sliding window
  window_radius_m: 0
optimizer:
  iters: 40000 #0
  batch_size: 4096
  learning_rate: 0.05
  weight_decay: 1e-7 # l2 regularization
eval:
  wandb_vis_on: False # log to wandb or not
  o3d_vis_on: False # visualize the mapping or not
  vis_freq_iters: 40000 #0 # reconstruct the mesh every x iterations
  save_freq_iters: 40000 #0 # save the model and octree every x iterations
  mesh_freq_frame: 1
  mc_res_m: 0.1 # reconstruction marching cubes resolution
  mc_with_octree: True # querying sdf only in certain levels of the octree
  mc_local: False
  mc_vis_level: 1
  save_map: False # save the sdf map or not
